<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>KerbalEngineer</RootNamespace>
    <AssemblyName>KerbalEngineer</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
    <LangVersion>latest</LangVersion>
    <KSPBT_ModRoot>$(MSBuildProjectDirectory)/../Output/KerbalEngineer</KSPBT_ModRoot>
    <KSPBT_ModPluginFolder></KSPBT_ModPluginFolder>
    <KSPBT_GenerateAssemblyAttribute>false</KSPBT_GenerateAssemblyAttribute>
    <KSPBT_GenerateDependencyAttributes>false</KSPBT_GenerateDependencyAttributes>
    <KSPBT_GenerateVersionFile>false</KSPBT_GenerateVersionFile>
    <KSPBT_ReferenceModAssemblies>false</KSPBT_ReferenceModAssemblies>
    <KSPBT_InstallCKANDependencies>false</KSPBT_InstallCKANDependencies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="KSPBuildTools" Version="1.1.1" PrivateAssets="all" />
    <ProjectReference Include="../KerbalEngineer.Unity/KerbalEngineer.Unity.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
</Project>
